export default {
  loadingSprite: require('../assets/pokeball.png'),
  normal: require('../assets/normal.png'),
  fighting: require('../assets/fighting.png'),
  flying: require('../assets/flying.png'),
  poison: require('../assets/poison.png'),
  ground: require('../assets/ground.png'),
  rock: require('../assets/rock.png'),
  bug: require('../assets/bug.png'),
  ghost: require('../assets/ghost.png'),
  steel: require('../assets/steel.png'),
  fire: require('../assets/fire.png'),
  water: require('../assets/water.png'),
  grass: require('../assets/grass.png'),
  electric: require('../assets/electric.png'),
  psychic: require('../assets/psychic.png'),
  ice: require('../assets/ice.png'),
  dragon: require('../assets/dragon.png'),
  fairy: require('../assets/fairy.png'),
  // unkown: require('../assets/unknown.png'),
  shadow: require('../assets/shadow.png'),
}
